# Goal: Target to translation
float64 target_dist     # distance (m)
float64[3] target_pose   # pos x y (m)
float64[2] target_vel   # vel vx vy (m/s)
uint8 mode_type 
uint8 loc_type 

uint8 ODOM_TYPE = 0
uint8 AMCL_TYPE = 1

uint8 DIST_TYPE = 0
uint8 POSE_TYPE = 1

---
# Result: Was the translation successful or not
bool success
---
# Feedback: Current error in distance
float64 current_error