#!/usr/bin/env python3
"""generate_cad_world.py — build cad_plant.world from csm/plant_cad.py.

    ros2 run trnav_2ws_gazebo generate_cad_world.py

This is the CUSTOMER'S plant, not ours. Every number comes from the two layout
drawings via `plant_cad.py`; nothing here is invented, and where the drawing is
silent the world is EMPTY rather than filled in with a guess. An empty patch on
screen is a question to ask the customer, and it should look like one.

WHY A SECOND GENERATOR RATHER THAN A FLAG ON THE FIRST.

`generate_world.py` builds `factory.world` from `plant.py` — the 43 x 26 m world
the fleet has actually been verified in. That world works and must keep working.
This one is ~10x larger in each direction, uses absolute CAD coordinates, and has
no robots in it yet. Sharing a generator between them would mean every change to
one is a risk to the other, for the sake of a `box()` helper.

ABSOLUTE COORDINATES.

The world origin is the CAD origin. A machine at x=113.25 in the drawing is at
x=113.25 in Gazebo, so any point can be read off one and typed into the other.
This costs nothing except that the interesting area is 100-290 m from the origin,
which is why the GUI camera below is parked over the cathode cell rather than at
the origin — at the origin you would be looking at bare ground 200 m from
anything.

WHAT IS DRAWN AND WHAT THAT MEANS

    walls           hall shell, 306 x 209 m               solid
    machines        13 bodies, coloured by family         solid
    lane paint      37 rectangles, flat on the floor      VISUAL ONLY
    junctions       30 crossings, small pale squares      VISUAL ONLY
    AGV positions   45 pads with a nose stripe            VISUAL ONLY
    coater LD/ULD   8 named stations, green / orange      VISUAL ONLY
    charging bays   4 pads                                VISUAL ONLY
    grid posts      every 50 m on the hall edge           solid, thin

Lane paint is paint. Making it collidable would put a 2.1 m kerb around every
drivable surface, which is the opposite of what a lane is. The same reasoning the
first generator learned the hard way with docking markers: a printed label is not
an obstacle.

NOT DRAWN, BECAUSE WE DO NOT YET KNOW IT — see
`docs/gazebo_world/open-questions.md`:

  * lane DIRECTION. The deck's slide 16 DOES carry direction arrows over the
    cell; they have not yet been read off into a direction per lane.
  * the anode cell (y < 100), which is in the hall but not in our model
  * WIP racks — the deck counts 2 gravure, 13 coater, 30 slitter, and we have
    the position of none of them
  * structural columns
  * 4 of the 5 cathode Big AGV chargers
  * the gravure and slitter LD/ULD stations. The coaters' are now placed from
    the deck; whether the other machines follow the same x-separated pattern is
    NOT checked, and must not be assumed.
"""

import math
import os
import sys

from csm import plant_cad as P

#: Machine bodies stand this tall. The drawings are a plan view and carry no
#: heights at all, so this is a DRAWING CONVENTION, not a measurement — enough to
#: read the layout in a 3-D view and to block a robot. Do not treat it as plant
#: data; if heights ever matter, they have to be asked for.
MACHINE_H = 3.0
WALL_H = 4.0
WALL_T = 0.30

#: Paint sits just off the floor so it renders above the ground plane instead of
#: fighting it for the same pixels.
PAINT_Z = 0.01
PAINT_T = 0.02

COLOURS = {
    "ASRS": (0.95, 0.75, 0.15, 1),      # store
    "GRV":  (0.30, 0.55, 0.90, 1),      # gravure
    "CTR":  (0.85, 0.35, 0.30, 1),      # coater
    "SLT":  (0.45, 0.80, 0.40, 1),      # slitter
}

HDR_TEMPLATE = """<?xml version="1.0"?>
<!--
  cad_plant.world — GENERATED by scripts/generate_cad_world.py from
  csm/plant_cad.py. DO NOT EDIT BY HAND.

  The FM2 cathode cell as the customer's drawings describe it, in ABSOLUTE CAD
  COORDINATES: a position here is the same position in the DWG. Sources and the
  full derivation are in plant_cad.py; what is still unknown is listed in
  docs/gazebo_world/open-questions.md.

  There are no robots in this world. It is the plant on its own, so that the
  geometry can be checked against the drawings before anything drives in it.
-->
<sdf version="1.6">
  <world name="cad_plant">
    <include><uri>model://sun</uri></include>
    <include><uri>model://ground_plane</uri></include>

    <physics type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
      <ode>
        <solver><type>quick</type><iters>100</iters><sor>1.3</sor></solver>
        <constraints>
          <cfm>0.0</cfm><erp>0.2</erp>
          <contact_max_correcting_vel>100.0</contact_max_correcting_vel>
          <contact_surface_layer>0.001</contact_surface_layer>
        </constraints>
      </ode>
    </physics>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.75 0.80 0.86 1</background>
      <shadows>true</shadows>
    </scene>

    <gui>
      <!-- Over the cathode cell, not the origin. The origin is bare floor 200 m
           from the nearest machine. -->
      <camera name="user_camera">
        <pose>{cam_x:.1f} {cam_y:.1f} {cam_z:.1f} 0 0.95 1.05</pose>
      </camera>
    </gui>

    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so">
      <ros>
        <namespace>/gazebo</namespace>
      </ros>
      <update_rate>30.0</update_rate>
    </plugin>
"""

FTR = """  </world>
</sdf>
"""


def box(name, x, y, z, sx, sy, sz, rgba, yaw=0.0, solid=True):
    """A static box. solid=False gives a VISUAL ONLY body — no collision."""
    r, g, b, a = rgba
    collision = (f"""
        <collision name="c"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry></collision>"""
                 if solid else "")
    return f"""
    <model name="{name}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 {yaw:.4f}</pose>
      <link name="link">{collision}
        <visual name="v">
          <geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
          <material>
            <ambient>{r} {g} {b} {a}</ambient>
            <diffuse>{r} {g} {b} {a}</diffuse>
          </material>
        </visual>
      </link>
    </model>"""


def rect(name, x0, y0, x1, y1, z, h, rgba, solid=True):
    """A box given by its extent rather than its centre — the form the CAD data
    is in, so the conversion happens once here instead of at every call site."""
    return box(name, (x0 + x1) / 2, (y0 + y1) / 2, z + h / 2,
               x1 - x0, y1 - y0, h, rgba, solid=solid)


def main():
    parts = []

    # ------------------------------------------------------------- shell
    (wx0, wx1), (wy0, wy1) = P.HALL_X, P.HALL_Y
    wall = (0.80, 0.80, 0.82, 1)
    parts.append(rect("wall_south", wx0, wy0 - WALL_T, wx1, wy0, 0, WALL_H, wall))
    parts.append(rect("wall_north", wx0, wy1, wx1, wy1 + WALL_T, 0, WALL_H, wall))
    parts.append(rect("wall_west", wx0 - WALL_T, wy0, wx0, wy1, 0, WALL_H, wall))
    parts.append(rect("wall_east", wx1, wy0, wx1 + WALL_T, wy1, 0, WALL_H, wall))

    # ------------------------------------------------------------ machines
    #
    # A COATER IS DRAWN AS AN OUTLINE, NOT A SOLID.
    #
    # COATER_X spans 24.83 m, which Q1 established is the coater CELL INCLUDING
    # ITS AGV APRON — its LD station is at x 125.58 and its ULD at 136.58, both
    # inside that span, and the spur runs in to x 124.56 to serve them. Drawing
    # the cell as a filled 3 m box put the machine on top of its own stations:
    # they were in the world, correctly placed, and completely hidden.
    #
    # It would also be wrong physically. A robot is meant to drive in there, so
    # the cell must not be an obstacle. Where the actual machine stands inside
    # the cell is NOT known — the drawing gives the cell, not the body — so the
    # honest thing is a boundary and empty floor, not a guessed smaller box.
    #
    # The gravure (6.9 m) and slitter (13.05 m) footprints are machine-sized
    # rather than cell-sized and stay solid, but whether they are also cells has
    # NOT been checked. See docs/gazebo_world/open-questions.md.
    for name, x0, y0, x1, y1 in P.machines():
        rgba = COLOURS.get(name[:4] if name == "ASRS" else name[:3],
                           (0.55, 0.55, 0.58, 1))
        if name.startswith("CTR"):
            t = 0.25
            for tag, ex0, ey0, ex1, ey1 in (
                    ("s", x0, y0, x1, y0 + t), ("n", x0, y1 - t, x1, y1),
                    ("w", x0, y0, x0 + t, y1), ("e", x1 - t, y0, x1, y1)):
                parts.append(rect(f"cell_{name}_{tag}", ex0, ey0, ex1, ey1,
                                  0, 0.35, rgba, solid=False))
            # Corner posts, so the cell reads as a bounded area from across the
            # hall without walling it off.
            for cx in (x0, x1):
                for cy in (y0, y1):
                    parts.append(box(f"cell_{name}_p{cx:.0f}_{cy:.0f}", cx, cy,
                                     1.5, 0.3, 0.3, 3.0, rgba, solid=False))
        else:
            parts.append(rect(f"m_{name}", x0, y0, x1, y1, 0, MACHINE_H, rgba))

    # -------------------------------------------------------------- lanes
    #
    # Painted, not built. See the module docstring: a collidable lane is a kerb.
    for i, (x0, y0, x1, y1) in enumerate(P.LANES, 1):
        parts.append(rect(f"lane_{i:02d}", x0, y0, x1, y1,
                          PAINT_Z, PAINT_T, (0.62, 0.66, 0.72, 1), solid=False))

    # A junction is where two painted rectangles overlap, so it is already
    # covered in lane grey. Marked in a second colour because these are the
    # points a reservation scheme has to arbitrate, and there are thirty of them
    # — a number that is much easier to believe once it is on screen.
    for i, (jx, jy) in enumerate(P.JUNCTIONS, 1):
        parts.append(box(f"junction_{i:02d}", jx, jy, PAINT_Z + PAINT_T + 0.005,
                         1.2, 1.2, 0.01, (0.95, 0.55, 0.15, 1), solid=False))

    # ------------------------------------------------------ AGV positions
    #
    # Drawn from the verbatim measured list, not from the grouped constants, so
    # what appears on screen is what is in the drawing. The nose stripe carries
    # the heading: a pad alone cannot show which way a robot parked there faces,
    # and the rot 0 / rot 180 pairing is the whole evidence for LD/ULD.
    l, w = P.ROBOT_3_5T[1], P.ROBOT_3_5T[0]
    for i, (px, py, rot) in enumerate(P.AGV_POSITIONS, 1):
        yaw = math.radians(rot)
        parts.append(box(f"agv_pos_{i:02d}", px, py, PAINT_Z + PAINT_T / 2,
                         l, w, PAINT_T, (0.25, 0.70, 0.35, 1), yaw, solid=False))
        parts.append(box(f"agv_nose_{i:02d}",
                         px + math.cos(yaw) * (l / 2 - 0.15),
                         py + math.sin(yaw) * (l / 2 - 0.15),
                         PAINT_Z + PAINT_T + 0.005,
                         0.30, w * 0.8, 0.01, (0.05, 0.35, 0.10, 1), yaw, solid=False))

    # --------------------------------------------------- coater spurs
    #
    # Each coater owns one spur, so paint them in the coater's own colour rather
    # than generic lane grey. A spur that belongs to a machine is a different
    # object from a through-lane, and the routing will have to treat it so.
    for i, (sy0, sy1, _side) in enumerate(P.COATER_SPUR, 1):
        parts.append(rect(f"spur_CTR{i}", P.COATER_SPUR_X[0], sy0,
                          P.COATER_SPUR_X[1], sy1,
                          PAINT_Z + PAINT_T, PAINT_T,
                          (0.85, 0.45, 0.40, 1), solid=False))

    # -------------------------------------------- spur-to-station links
    #
    # One per station, hugging its east edge, running to the spur. ALL EIGHT ARE
    # DERIVED from the project lead's sketch — none is in the drawing — so all
    # eight are drawn at reduced opacity. Nothing here should read as measured.
    for x0, y0, x1, y1, ci, kind in P.coater_connectors():
        parts.append(rect(f"link_CTR{ci}_{kind}", x0, y0, x1, y1,
                          PAINT_Z + PAINT_T, PAINT_T,
                          (0.85, 0.45, 0.40, 0.5), solid=False))

    # The two long north-south roads on the ULD column, from the lane data. These
    # ARE measured, and they are NOT connectors: each runs from one coater's spur
    # past the next coater's station, linking adjacent rows.
    for li, (x0, y0, x1, y1) in enumerate(P.COATER_LINK_ROADS, 1):
        parts.append(rect(f"coater_link_{li}", x0, y0, x1, y1,
                          PAINT_Z, PAINT_T, (0.62, 0.66, 0.72, 1), solid=False))

    # ------------------------------------------------- coater LD / ULD
    #
    # The first stations in this world that are NAMED rather than merely
    # measured. The deck [S16] says Coater LD 4EA and Coater ULD 4EA; block
    # `zw$4E78` puts LD at x 125.58 and ULD at x 136.58, both at the same y —
    # they differ in x, not y.
    #
    # Drawn as a pad plus a post so they read as stations from across a 300 m
    # hall, where a flat pad is invisible. The post is VISUAL ONLY: a station is
    # a place to stand, not an obstacle.
    LD_RGBA = (0.15, 0.75, 0.30, 1)
    ULD_RGBA = (0.95, 0.55, 0.10, 1)
    for i, sy in enumerate(P.COATER_STATION_Y):
        for kind, sx, rgba in (("ld", P.COATER_LD_X, LD_RGBA),
                               ("uld", P.COATER_ULD_X, ULD_RGBA)):
            # The two symbols of one station, facing each other across it.
            for j, dy in ((0, -P.COATER_STATION_PAIR / 2),
                          (1, +P.COATER_STATION_PAIR / 2)):
                parts.append(box(f"ctr{i+1}_{kind}_{j}", sx, sy + dy,
                                 PAINT_Z + PAINT_T / 2, l, w, PAINT_T,
                                 rgba, 0.0, solid=False))
            parts.append(box(f"ctr{i+1}_{kind}_post", sx, sy, 1.2,
                             0.35, 0.35, 2.4, rgba, solid=False))

    # CTR4's ULD is inferred, not measured — drawn hollow-pale so the world does
    # not present a guess with the same confidence as a measurement.
    for i, measured in enumerate(P.COATER_ULD_MEASURED):
        if not measured:
            parts.append(box(f"ctr{i+1}_uld_inferred", P.COATER_ULD_X,
                             P.COATER_STATION_Y[i], 2.8,
                             0.9, 0.9, 0.9, (0.95, 0.55, 0.10, 0.35), solid=False))

    # ------------------------------------------------------- WIP racks
    #
    # Access points, not slots — see plant_cad.WIP_ACCESS_X. Drawn as pads on
    # the two columns, one per position, in a colour of their own so they are
    # never mistaken for a machine station.
    WIP_RGBA = (0.55, 0.35, 0.75, 1)
    for gi, (ya, yb) in enumerate(P.WIP_GROUP_Y, 1):
        for ci, wx in enumerate(P.WIP_ACCESS_X, 1):
            for pi, wy in enumerate((ya, yb), 1):
                parts.append(box(f"wip_g{gi}_c{ci}_{pi}", wx, wy,
                                 PAINT_Z + PAINT_T / 2, l, w, PAINT_T,
                                 WIP_RGBA, 0.0, solid=False))
        # One post per group, so four groups read as four racks from a distance.
        parts.append(box(f"wip_g{gi}_post", sum(P.WIP_ACCESS_X) / 2,
                         (ya + yb) / 2, 1.0, 0.30, 0.30, 2.0,
                         WIP_RGBA, solid=False))

    # ------------------------------------------------------------ charging
    cw, ch = P.CHARGING_BAY_SIZE
    for group, bays in P.CHARGING.items():
        for i, (bx, by) in enumerate(bays, 1):
            parts.append(box(f"charge_{group}_{i}", bx, by, PAINT_Z + PAINT_T / 2,
                             cw, ch, PAINT_T, (0.25, 0.45, 0.85, 1), solid=False))

    # ---------------------------------------------------------- grid posts
    #
    # A 306 m hall has no scale on screen — everything is far away and the eye
    # has nothing to measure against. A post every 50 m along the south and west
    # walls gives one, and because the world is in absolute CAD coordinates the
    # post at x=150 IS x=150 in the drawing.
    posts = 0
    gx = int(math.ceil(wx0 / 50.0) * 50)
    while gx <= wx1:
        parts.append(box(f"grid_x{gx}", gx, wy0 + 1.0, 1.5,
                         0.25, 0.25, 3.0, (0.15, 0.15, 0.18, 1)))
        posts += 1
        gx += 50
    gy = int(math.ceil(wy0 / 50.0) * 50)
    while gy <= wy1:
        parts.append(box(f"grid_y{gy}", wx0 + 1.0, gy, 1.5,
                         0.25, 0.25, 3.0, (0.15, 0.15, 0.18, 1)))
        posts += 1
        gy += 50

    # The camera looks at the middle of what is actually modelled — the machine
    # bodies — rather than the middle of the hall, half of which is the anode
    # cell we do not model and which is therefore empty floor.
    ms = P.machines()
    cx = sum((m[1] + m[3]) / 2 for m in ms) / len(ms)
    cy = sum((m[2] + m[4]) / 2 for m in ms) / len(ms)
    hdr = HDR_TEMPLATE.format(cam_x=cx - 70, cam_y=cy - 75, cam_z=95)

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, "..", "worlds", "cad_plant.world"))
    with open(out, "w") as f:
        f.write(hdr + "".join(parts) + FTR)

    print(f"wrote {out}")
    print(f"  hall      {wx1 - wx0:.0f} x {wy1 - wy0:.0f} m, absolute CAD coordinates")
    print(f"  machines  {len(ms)}")
    print(f"  lanes     {len(P.LANES)} painted, {len(P.JUNCTIONS)} junctions")
    print(f"  AGV pads  {len(P.AGV_POSITIONS)}")
    print(f"  charging  {sum(len(b) for b in P.CHARGING.values())} bays, {posts} grid posts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
