#!/usr/bin/env python3
"""generate_world.py — build factory.world from csm/plant.py.

    ros2 run trnav_2ws_gazebo generate_world.py

The world is GENERATED, not hand-edited. plant.py is the single source of truth
for where the machines stand; a hand-maintained world file drifts from it, and
then the simulation is quietly testing a different factory from the one the CSM
believes in. Regenerate after any change to plant.py.
"""

import math
import os
import sys

from csm import plant

HDR = """<?xml version="1.0"?>
<!--
  factory.world — GENERATED by scripts/generate_world.py from csm/plant.py.
  DO NOT EDIT BY HAND: regenerate instead, or the world and the CSM's model of
  the plant will disagree and every experiment will be measuring the difference.

  Layout follows the customer documents (see plant.py for the source list):
  two machine rows facing a pair of aisles, ports combing off them — the shape
  of the AGV route map in the system deck, not an open floor.
-->
<sdf version="1.6">
  <world name="factory">
    <include><uri>model://sun</uri></include>
    <include><uri>model://ground_plane</uri></include>

    <physics type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
      <ode>
        <solver><type>quick</type><iters>100</iters><sor>1.3</sor></solver>
        <constraints>
          <cfm>0.0</cfm><erp>0.2</erp>
          <contact_max_correcting_vel>100.0</contact_max_correcting_vel>
          <contact_surface_layer>0.001</contact_surface_layer>
        </constraints>
      </ode>
    </physics>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.75 0.80 0.86 1</background>
      <shadows>true</shadows>
    </scene>

    <gui>
      <camera name="user_camera">
        <pose>-14 -22 22 0 0.62 0.9</pose>
      </camera>
    </gui>

    <!-- GROUND TRUTH for every model, on ONE topic. Every robot looks itself up
         by name on /gazebo/model_states.

         This plugin is NOT optional. Without it the topic has no publisher, no
         robot ever gets a pose, and — because a route is planned from where the
         robot IS — nothing can be dispatched at all. The first generated world
         omitted it and the whole fleet sat still with "no pose".

         The per-model p3d plugin does not survive multi-robot: each copy needs
         its own ROS namespace AND its own plugin name, and even with both the
         bindings came out crossed. One world-level publisher has no per-model
         plumbing to get wrong. -->
    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so">
      <ros>
        <namespace>/gazebo</namespace>
      </ros>
      <update_rate>30.0</update_rate>
    </plugin>
"""

#: Marker centre height = docking lens height (base_link CAM_Z 0.55 + wheel
#: radius 0.125). See the note where the markers are placed.
MARKER_Z = 0.675

FTR = """  </world>
</sdf>
"""


def box(name, x, y, z, sx, sy, sz, rgba, solid=True):
    """A static box. solid=False gives a VISUAL ONLY body — no collision.

    Markers are printed labels, not obstacles. Giving them collision made them
    physical objects standing 10 cm proud of each machine face, which ate half
    the docking gap: robot edge 6.771 against a plate front at 6.890, so 0.119 m
    where 0.229 m was designed for.
    """
    r, g, b, a = rgba
    collision = (f"""
        <collision name="c"><geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry></collision>"""
                 if solid else "")
    return f"""
    <model name="{name}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>
      <link name="link">{collision}
        <visual name="v">
          <geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>
          <material>
            <ambient>{r} {g} {b} {a}</ambient>
            <diffuse>{r} {g} {b} {a}</diffuse>
          </material>
        </visual>
      </link>
    </model>"""


#: An overhead camera looking straight down at the whole hall.
#:
#: WHY THE WORLD CARRIES ONE. Capturing the Gazebo WINDOW does not work here:
#: gzclient is an XWayland client, and an X11 root grab of it returns a black
#: frame. A camera inside the simulation is not a picture of a window, it is a
#: picture of the world — so it works headless, over ssh, and while paused.
#:
#: It publishes on a ROS topic through gazebo_ros_camera, so anything that
#: wants a frame subscribes and takes one. `Tools/rule_watch/` uses it to
#: photograph the moment a traffic rule fires.
#:
#: Static, high, and orthographic-ish (a narrow field of view from far up), so
#: the picture is a plan view that can be measured rather than a perspective
#: shot that cannot.
OVERHEAD = """
    <model name="overhead_camera">
      <static>true</static>
      <pose>{cx:.3f} {cy:.3f} {height:.3f} 0 1.5708 0</pose>
      <link name="link">
        <sensor name="overhead" type="camera">
          <update_rate>4.0</update_rate>
          <camera>
            <horizontal_fov>{fov:.4f}</horizontal_fov>
            <image><width>1600</width><height>1000</height><format>R8G8B8</format></image>
            <clip><near>1.0</near><far>{far:.1f}</far></clip>
          </camera>
          <plugin name="overhead_camera" filename="libgazebo_ros_camera.so">
            <ros><namespace>/overhead</namespace></ros>
            <camera_name>overhead</camera_name>
            <frame_name>overhead_link</frame_name>
          </plugin>
        </sensor>
      </link>
    </model>
"""


def overhead_camera(w, e, s, n):
    """A camera far enough up to see the whole hall, looking straight down."""
    import math
    cx, cy = (w + e) / 2.0, (s + n) / 2.0
    width = e - w
    height = 60.0                      # metres above the floor
    fov = 2.0 * math.atan((width / 2.0) * 1.06 / height)
    return OVERHEAD.format(cx=cx, cy=cy, height=height, fov=fov, far=height + 10.0)


def main():
    w, e, s, n = plant.HALL_W, plant.HALL_E, plant.HALL_S, plant.HALL_N
    t, h = plant.WALL_T, 2.0
    parts = [HDR]

    # Walls, on the hall boundary.
    parts.append(box("wall_north", (w + e) / 2, n, h / 2, e - w, t, h, (0.8, 0.8, 0.82, 1)))
    parts.append(box("wall_south", (w + e) / 2, s, h / 2, e - w, t, h, (0.8, 0.8, 0.82, 1)))
    parts.append(box("wall_west", w, (s + n) / 2, h / 2, t, n - s, h, (0.8, 0.8, 0.82, 1)))
    parts.append(box("wall_east", e, (s + n) / 2, h / 2, t, n - s, h, (0.8, 0.8, 0.82, 1)))

    parts.append(overhead_camera(w, e, s, n))

    # One box per solid machine. Colour by family so the line reads at a glance.
    for name, (mx, my) in plant.OBSTACLES.items():
        if name == "ASRS":
            rgba = (0.95, 0.75, 0.15, 1)          # store
        elif name.startswith("GRV"):
            rgba = (0.30, 0.55, 0.90, 1)          # gravure
        elif name.startswith("CTR"):
            rgba = (0.85, 0.35, 0.30, 1)          # coater
        elif name.startswith("SLT"):
            rgba = (0.45, 0.80, 0.40, 1)          # slitter
        else:
            rgba = (0.55, 0.55, 0.58, 1)          # WIP rack
        parts.append(box(f"m_{name}", mx, my, 0.6,
                         plant.MACHINE_W, plant.MACHINE_D, 1.2, rgba))

    # The docking markers — the QR/ArUco square the robot watches to close the
    # last couple of metres. One per port, in line with that port.
    #
    # Offset along the marker's OWN outward normal. An earlier version worked
    # the direction out from the sign of y and got it backwards, putting every
    # north-row marker 6 cm INSIDE its machine box (face at y=7.0, box spanning
    # 7..9) — mathematically irrelevant, since the controller uses the face
    # position, but invisible, so there was nothing to check by eye. Deriving
    # the offset from the normal cannot get the sign wrong.
    for name, (mx, my, myaw) in plant.MARKERS.items():
        nx, ny = math.cos(myaw), math.sin(myaw)
        # 0.13 m plate with an 0.08 m black square — the size is SET BY THE
        # CLOSEST POINT, not chosen for looks. At the docked standoff the lens
        # is 0.16 m away and sees 0.22 m of width, so anything bigger overflows
        # exactly when the robot needs it most. At the approach point 2.2 m out
        # the plate is still ~35 px across at 640 wide, which ArUco resolves.
        # The first version was 0.50 m and filled the frame completely at dock.
        # AT LENS HEIGHT. The camera sits at CAM_Z = 0.55 in base_link and
        # base_link is a wheel radius (0.125) above the floor, so the lens is at
        # 0.675. A marker higher than that slides off the TOP of the frame right
        # at the end of the approach — at 0.9 the rise was 29 deg of elevation
        # against a 27 deg vertical half-angle, so it was in view the whole way
        # in and then gone exactly when it was needed. Level with the lens, it
        # stays centred. Keep in step with CAM_Z in foil_a082.urdf.xacro.
        parts.append(box(f"marker_{name}", mx + nx * 0.02, my + ny * 0.02, MARKER_Z,
                         0.13, 0.02, 0.13, (0.97, 0.97, 0.97, 1), solid=False))
        parts.append(box(f"markerdot_{name}", mx + nx * 0.03, my + ny * 0.03, MARKER_Z,
                         0.08, 0.01, 0.08, (0.05, 0.05, 0.05, 1), solid=False))

        # EVERY MARKER IS DIFFERENT. The id is drawn as white cells in a row
        # across the black square — a plain binary tally, five bits, enough for
        # the 25 ports. The robot checks it before entering, so arriving at the
        # wrong bay is refused rather than docked against and reported as a
        # success. Drawn rather than merely numbered so it can be read off the
        # screen as well as out of the log.
        marker_id = plant.MARKER_IDS[name]
        px, py = -ny, nx                        # across the face of the marker
        for bit in range(5):
            if not (marker_id >> bit) & 1:
                continue
            off = (bit - 2) * 0.015
            parts.append(box(
                f"markerbit_{name}_{bit}",
                mx + nx * 0.04 + px * off, my + ny * 0.04 + py * off, MARKER_Z,
                0.009, 0.005, 0.034, (0.97, 0.97, 0.97, 1), solid=False))

    parts.append(FTR)

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "worlds", "factory.world")
    out = os.path.normpath(out)
    with open(out, "w") as f:
        f.write("".join(parts))
    print(f"wrote {out}")
    print(f"  hall {e - w:.0f} x {n - s:.0f} m, {len(plant.OBSTACLES)} machines, "
          f"{len(plant.DOCKS)} docking ports")


if __name__ == "__main__":
    sys.exit(main())
